# Generated by Django 5.1.4 on 2026-09-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(db_index=True, default=0, verbose_name='orden')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='galeria/', verbose_name='imagen')),
                ('imagen_ruta', models.CharField(blank=True, max_length=200, verbose_name='ruta de imagen')),
                ('alt', models.CharField(blank=True, max_length=140, verbose_name='texto alternativo')),
                ('visible', models.BooleanField(default=True, verbose_name='visible')),
            ],
            options={
                'verbose_name': 'foto de la galería',
                'verbose_name_plural': 'fotos de la galería',
                'ordering': ['orden', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HelpItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(db_index=True, default=0, verbose_name='orden')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('slug', models.SlugField(help_text='Se usa como ancla en la dirección: /ayuda#envios. Cambiarlo rompe los enlaces.', unique=True, verbose_name='slug')),
                ('pregunta', models.CharField(max_length=160, verbose_name='pregunta')),
                ('respuesta', models.TextField(help_text='Un párrafo por línea. Las líneas en blanco se ignoran.', verbose_name='respuesta')),
                ('puntos', models.TextField(blank=True, help_text='Opcional. Un punto por línea, cuando la respuesta se lee mejor como lista.', verbose_name='lista de puntos')),
                ('nota', models.CharField(blank=True, help_text='Opcional. Una aclaración corta debajo de la respuesta.', max_length=300, verbose_name='nota al pie')),
                ('visible', models.BooleanField(default=True, verbose_name='visible')),
            ],
            options={
                'verbose_name': 'pregunta de ayuda',
                'verbose_name_plural': 'preguntas de ayuda',
                'ordering': ['orden', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(db_index=True, default=0, verbose_name='orden')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='inicio/', verbose_name='imagen')),
                ('imagen_ruta', models.CharField(blank=True, max_length=200, verbose_name='ruta de imagen')),
                ('alt', models.CharField(blank=True, help_text='Qué se ve en la foto. Lo leen los lectores de pantalla y los buscadores.', max_length=140, verbose_name='texto alternativo')),
                ('visible', models.BooleanField(default=True, verbose_name='visible')),
            ],
            options={
                'verbose_name': 'foto del inicio',
                'verbose_name_plural': 'fotos del inicio',
                'ordering': ['orden', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(help_text='Con indicativo de país y sin espacios ni signos. Ejemplo: 573203684500', max_length=20, verbose_name='WhatsApp')),
                ('whatsapp_visible', models.CharField(help_text='Como se lee en la página. Ejemplo: +57 320 368 4500', max_length=30, verbose_name='WhatsApp como se muestra')),
                ('email', models.EmailField(max_length=254, verbose_name='correo')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('tiktok', models.URLField(blank=True, verbose_name='TikTok')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('ubicacion', models.CharField(blank=True, max_length=80, verbose_name='ubicación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'datos del negocio',
                'verbose_name_plural': 'datos del negocio',
            },
        ),
        migrations.CreateModel(
            name='ValueProp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(db_index=True, default=0, verbose_name='orden')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('icono', models.CharField(choices=[('hand-heart', 'Mano con corazón'), ('palette', 'Paleta de colores'), ('gift', 'Regalo'), ('messages-square', 'Mensajes'), ('sparkles', 'Destellos'), ('truck', 'Camión'), ('flower', 'Flor'), ('clock', 'Reloj')], default='hand-heart', max_length=20, verbose_name='icono')),
                ('titulo', models.CharField(max_length=80, verbose_name='título')),
                ('descripcion', models.CharField(max_length=200, verbose_name='descripción')),
                ('visible', models.BooleanField(default=True, verbose_name='visible')),
            ],
            options={
                'verbose_name': 'motivo para comprar',
                'verbose_name_plural': 'motivos para comprar',
                'ordering': ['orden', 'id'],
                'abstract': False,
            },
        ),
    ]
