# Generated by Django 5.1.4 on 2026-09-22 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowerColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(db_index=True, default=0, verbose_name='orden')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='slug')),
                ('label', models.CharField(max_length=40, verbose_name='nombre')),
                ('swatch', models.CharField(help_text='Color en hexadecimal para el botón, por ejemplo #f2789f', max_length=9, verbose_name='muestra')),
                ('visible', models.BooleanField(default=True, verbose_name='visible')),
            ],
            options={
                'verbose_name': 'color de flor',
                'verbose_name_plural': 'colores de flor',
                'ordering': ['orden', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ribbon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(db_index=True, default=0, verbose_name='orden')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='slug')),
                ('label', models.CharField(max_length=60, verbose_name='nombre')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='armador/listones/', verbose_name='imagen')),
                ('imagen_ruta', models.CharField(blank=True, max_length=200, verbose_name='ruta de imagen')),
                ('aspect', models.FloatField(default=1.0, verbose_name='proporción')),
                ('visible', models.BooleanField(default=True, verbose_name='visible')),
            ],
            options={
                'verbose_name': 'listón',
                'verbose_name_plural': 'listones',
                'ordering': ['orden', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wrapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(db_index=True, default=0, verbose_name='orden')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='slug')),
                ('label', models.CharField(max_length=60, verbose_name='nombre')),
                ('tamano', models.CharField(help_text='En palabras, como lo lee el cliente: Grande, Mediana, Pequeña.', max_length=40, verbose_name='tamaño')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='armador/envolturas/', verbose_name='imagen')),
                ('imagen_ruta', models.CharField(blank=True, max_length=200, verbose_name='ruta de imagen')),
                ('aspect', models.FloatField(help_text='Ancho dividido alto de la foto recortada.', verbose_name='proporción')),
                ('cluster_x', models.FloatField(help_text='Fracción de la caja (0 a 1).', verbose_name='centro del ramo X')),
                ('cluster_y', models.FloatField(help_text='Fracción de la caja (0 a 1).', verbose_name='centro del ramo Y')),
                ('cluster_r', models.FloatField(help_text='Fracción del ancho de la envoltura.', verbose_name='radio del ramo')),
                ('escala_flores', models.FloatField(help_text='Cuánto se ven las flores en esta envoltura. Una envoltura pequeña las hace ver más grandes.', verbose_name='escala de las flores')),
                ('nudo_x', models.FloatField(help_text='Dónde amarra el listón, fracción de la caja.', verbose_name='nudo X')),
                ('nudo_y', models.FloatField(help_text='Dónde amarra el listón, fracción de la caja.', verbose_name='nudo Y')),
                ('nudo_ancho', models.FloatField(help_text='Fracción del ancho de la caja.', verbose_name='ancho del nudo')),
                ('capacidad', models.PositiveIntegerField(help_text='Cuántas piezas caben de verdad en esta envoltura.', verbose_name='capacidad')),
                ('visible', models.BooleanField(default=True, verbose_name='visible')),
            ],
            options={
                'verbose_name': 'envoltura',
                'verbose_name_plural': 'envolturas',
                'ordering': ['orden', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(db_index=True, default=0, verbose_name='orden')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='slug')),
                ('label', models.CharField(max_length=60, verbose_name='nombre')),
                ('rol', models.CharField(choices=[('face', 'Cara — flor abierta y grande, va abajo y al frente'), ('stem', 'Tallo — va arriba y parada, en arco'), ('spike', 'Espiga — alta, marca la silueta del ramo'), ('filler', 'Relleno — pequeña, se mete en las junturas'), ('green', 'Follaje — va al fondo, abriéndose hacia los lados')], max_length=10, verbose_name='rol')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='armador/flores/', verbose_name='imagen')),
                ('imagen_ruta', models.CharField(blank=True, max_length=200, verbose_name='ruta de imagen')),
                ('ancho', models.FloatField(help_text='Ancho de la foto en unidades del escenario (el escenario mide 1000), a escala real frente a las demás flores.', verbose_name='ancho')),
                ('alto', models.FloatField(help_text='Alto en las mismas unidades que el ancho.', verbose_name='alto')),
                ('anchor_x', models.FloatField(help_text='Centro de la cabeza, en fracción del ancho de la foto (0 a 1).', verbose_name='anclaje X')),
                ('anchor_y', models.FloatField(help_text='Centro de la cabeza, en fracción del alto de la foto (0 a 1).', verbose_name='anclaje Y')),
                ('tallo_imagen', models.ImageField(blank=True, null=True, upload_to='armador/flores/', verbose_name='imagen con tallo')),
                ('tallo_imagen_ruta', models.CharField(blank=True, max_length=200, verbose_name='ruta de imagen con tallo')),
                ('tallo_ancho', models.FloatField(blank=True, null=True, verbose_name='ancho con tallo')),
                ('tallo_alto', models.FloatField(blank=True, null=True, verbose_name='alto con tallo')),
                ('tallo_anchor_x', models.FloatField(blank=True, null=True, verbose_name='anclaje X con tallo')),
                ('tallo_anchor_y', models.FloatField(blank=True, null=True, verbose_name='anclaje Y con tallo')),
                ('visible', models.BooleanField(default=True, verbose_name='visible')),
                ('color_base', models.ForeignKey(blank=True, help_text='Con qué color está hecha la foto de arriba. Vacío si la flor no cambia de color.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flores_base', to='builder.flowercolor', verbose_name='color de la foto original')),
            ],
            options={
                'verbose_name': 'flor',
                'verbose_name_plural': 'flores',
                'ordering': ['orden', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlowerVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='armador/flores/', verbose_name='imagen')),
                ('imagen_ruta', models.CharField(blank=True, max_length=200, verbose_name='ruta de imagen')),
                ('tallo_imagen', models.ImageField(blank=True, null=True, upload_to='armador/flores/', verbose_name='imagen con tallo')),
                ('tallo_imagen_ruta', models.CharField(blank=True, max_length=200, verbose_name='ruta de imagen con tallo')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='builder.flowercolor', verbose_name='color')),
                ('flor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='builder.flower', verbose_name='flor')),
            ],
            options={
                'verbose_name': 'variante de color',
                'verbose_name_plural': 'variantes de color',
                'ordering': ['flor', 'color'],
                'constraints': [models.UniqueConstraint(fields=('flor', 'color'), name='una_variante_por_flor_y_color')],
            },
        ),
    ]
