# Generated by Django 5.1.4 on 2026-09-22 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(db_index=True, default=0, verbose_name='orden')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('titulo', models.CharField(max_length=80, verbose_name='título')),
                ('subtitulo', models.CharField(blank=True, max_length=120, verbose_name='subtítulo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias/', verbose_name='imagen')),
                ('imagen_ruta', models.CharField(blank=True, help_text='Foto que ya vive en el frontend, por ejemplo /categories/flores.webp', max_length=200, verbose_name='ruta de imagen')),
                ('visible', models.BooleanField(default=True, help_text='Si se desmarca, la categoría desaparece del menú y del inicio.', verbose_name='visible')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['orden', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(db_index=True, default=0, verbose_name='orden')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('nombre', models.CharField(max_length=140, verbose_name='nombre')),
                ('precio', models.PositiveIntegerField(help_text='En pesos colombianos, sin decimales ni puntos. Ejemplo: 45000', verbose_name='precio')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='imagen')),
                ('imagen_ruta', models.CharField(blank=True, max_length=200, verbose_name='ruta de imagen')),
                ('etiqueta', models.CharField(blank=True, help_text='Distintivo sobre la foto, por ejemplo "Nuevo" o "Más vendido".', max_length=40, verbose_name='etiqueta')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('incluye', models.TextField(blank=True, verbose_name='incluye')),
                ('disponible', models.BooleanField(default=True, help_text='Si se desmarca, el producto deja de aparecer en la tienda.', verbose_name='disponible')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalog.category', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['orden', 'id'],
                'abstract': False,
                'indexes': [models.Index(fields=['categoria', 'disponible'], name='catalog_pro_categor_fabef6_idx')],
            },
        ),
    ]
